server:
  port: 18081
spring:
  application:
    name: goods
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 设置 jdbc 连接串 useSSL=false 解决 Bad handshake 问题 https://opensource.actionsky.com/20200514-mysql/
    url: jdbc:mysql://192.168.211.132:3306/changgou_goods?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
logging:
  level.com: debug
# 开启驼峰命名设置，自动将下划线形式转化为驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true